name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3

      - name: Execute Gradle build
        run: ./gradlew build

  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo checkstyle

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo coverage