name: Java CI with Gradle, CheckStyle and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3

      - name: Execute Gradle build
        run: gradle clean build

      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: |
            build/classes
            build/jacoco/test.exec

  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    name: checkstyle

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: config/checkstyle/checkstyle.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'

  coverage:
    needs: build
    runs-on: ubuntu-latest
    name: coverage

    steps:
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: code-coverage

      - run: ls

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download JacocoCLI
        run: wget https://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.8.11/jacoco-0.8.11.zip -O jacoco-0.8.11.zip

      - name: Extract JacocoCLI
        run: unzip jacoco-0.8.11.zip -d jacoco-0.8.11

      - name: Generate report
        run: java -jar jacoco-0.8.11/lib/jacococli.jar report build/jacoco/test.exec --classfiles classes/ --xml jacocoTestReport.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Coverage Results
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 60